name:  First github actions
on: [push] #push,pull_request,deployment_status
jobs: 
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: tree