name:  First github actions
on: [push] #push,pull_request,deployment_status
jobs: 
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Build a project
                run: yarn build
          
            
           